### ISSUE TITLE
http://ifconfig.pro/freedooooom returns 500 internal service error

### ISSUE THREAD

**Issue by s00ner** [pronto/ifconfig.pro#1]
Title says it all.

**Comment by s00ner** [comment]
curl http://ifconfig.pro/freedooooom

> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> 
> <h1>Internal Server Error</h1>
> 
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by pronto** [comment]
hashtag: wontfix
